openapi: 3.0.3
info:
  title: Reelix Discovery Agent API
  version: 0.1.0
paths:
  /health:
    get:
      operationId: health
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  service: { type: string }
