/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Reelix Discovery Agent API
 * OpenAPI spec version: 0.1.0
 */
export type Health200 = {
  service?: string;
  status?: string;
};



export type healthResponse = {
  data: Health200;
  status: number;
}

export const getHealthUrl = () => {


  return `/health`
}

export const health = async ( options?: RequestInit): Promise<healthResponse> => {
  const res = await fetch(getHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}


