"""
/discovery/telemetry endpoints. Telemetry and logging for discovery results.
"""

import time
import asyncio
from fastapi import APIRouter, Depends
from fastapi.responses import JSONResponse

from app.deps.deps import get_logger
from app.deps.supabase_client import get_current_user_id
from app.deps.deps_redis_caches import get_why_cache
from app.infrastructure.cache.why_cache import WhyCache, CachedWhy
from app.schemas import FinalRecsRequest

router = APIRouter(tags=["telemetry"])

PIPELINE_VERSION = "RecommendPipeline@v2"


@router.post("/telemetry/final_recs")
async def log_final_recommendations(
    req: FinalRecsRequest,
    user_id: str = Depends(get_current_user_id),
    logger=Depends(get_logger),
    why_cache: WhyCache = Depends(get_why_cache),
):
    """Log final recommendations shown to user and cache why explanations."""
    # Fire-and-forget logging + cache updates to avoid blocking the client
    async def _bg() -> None:
        await logger.log_why(
            endpoint=req.endpoint,
            query_id=req.query_id,
            final_recs=req.final_recs,
        )
        # Best-effort cache write; ignore errors
        try:
            values: dict[int, CachedWhy] = {}
            now = time.time()
            for r in req.final_recs:
                # Only cache if this why was newly generated by the LLM
                if r.why_source.lower() == "cache":
                    continue

                values[r.media_id] = CachedWhy(
                    why_md=r.why,
                    imdb_rating=r.imdb_rating,
                    rt_rating=r.rt_rating,
                    created_at=now,
                    taste_version=PIPELINE_VERSION,
                )

            if values:
                await why_cache.set_many(
                    user_id=user_id,
                    media_type=req.media_type,
                    values=values,
                )
        except Exception:
            # Cache errors shouldn't break logging
            pass

    asyncio.create_task(_bg())
    return JSONResponse({"ok": True})