from reelix_core.config import (
    QDRANT_API_KEY,
    QDRANT_ENDPOINT,
    QDRANT_MOVIE_COLLECTION_NAME,
)
from reelix_retrieval.filter_builder import build_qfilter
from reelix_retrieval.vectorstore import connect_qdrant


SEED_MOVIES = {
    'Action': [{'title': 'Mad Max: Fury Road',
   'year': 2015,
   'vibes': ['Fast-paced', 'Action-packed', 'High-stakes'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg'},
  {'title': 'John Wick',
   'year': 2014,
   'vibes': ['Fast-paced', 'Action-packed'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg'},
  {'title': 'Mission: Impossible - Fallout',
   'year': 2018,
   'vibes': ['Espionage', 'High-stakes', 'Fast-paced'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg'},
  {'title': 'Skyfall',
   'year': 2012,
   'vibes': ['Espionage', 'High-stakes'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/d0IVecFQvsGdSbnMAHqiYsNYaJT.jpg'},
  {'title': 'The Raid: Redemption',
   'year': 2011,
   'vibes': ['Fast-paced', 'Action-packed'],
   'poster_url': ''},
  {'title': 'Die Hard',
   'year': 1988,
   'vibes': ['High-stakes', 'Action-packed'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/aJCpHDC6RoGz7d1Fzayl019xnxX.jpg'},
  {'title': 'Hard Boiled',
   'year': 1992,
   'vibes': ['Action-packed', 'Fast-paced'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/r6lY3VlMAtYyJ4nEsXM1BWdwafs.jpg'},
  {'title': 'The Bourne Ultimatum',
   'year': 2007,
   'vibes': ['Espionage', 'Fast-paced'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/15rMz5MRXFp7CP4VxhjYw4y0FUn.jpg'},
  {'title': 'Edge of Tomorrow',
   'year': 2014,
   'vibes': ['Fast-paced', 'Action-packed'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/nBM9MMa2WCwvMG4IJ3eiGUdbPe6.jpg'},
  {'title': 'The Dark Knight',
   'year': 2008,
   'vibes': ['High-stakes', 'Action-packed'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg'}],
 'Adventure': [{'title': 'Raiders of the Lost Ark',
   'year': 1981,
   'vibes': ['Epic scale', 'Grand journey'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg'},
  {'title': 'The Lord of the Rings: The Fellowship of the Ring',
   'year': 2001,
   'vibes': ['Epic scale', 'Grand journey', 'Visually-stunning'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg'},
  {'title': 'Spirited Away',
   'year': 2001,
   'vibes': ['Whimsical', 'Visually-stunning'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg'},
  {'title': 'Life of Pi',
   'year': 2012,
   'vibes': ['Visually-stunning', 'Grand journey'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/iLgRu4hhSr6V1uManX6ukDriiSc.jpg'},
  {'title': 'Up',
   'year': 2009,
   'vibes': ['Whimsical', 'Grand journey'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg'},
  {'title': 'The Princess Bride',
   'year': 1987,
   'vibes': ['Whimsical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/dvjqlp2sAhUeFjUOfQDgqwpphHj.jpg'},
  {'title': 'The Adventures of Tintin',
   'year': 2011,
   'vibes': ['Grand journey', 'Visually-stunning'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/fQZ3sLR1Fi63NMsNRbjm9q5qODJ.jpg'},
  {'title': 'The Revenant',
   'year': 2015,
   'vibes': ['Grand journey', 'Epic scale'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/ji3ecJphATlVgWNY0B0RVXZizdf.jpg'},
  {'title': 'The Secret Life of Walter Mitty',
   'year': 2013,
   'vibes': ['Whimsical', 'Grand journey'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/tY6ypjKOOtujhxiSwTmvA4OZ5IE.jpg'},
  {'title': 'Moana',
   'year': 2016,
   'vibes': ['Grand journey', 'Visually-stunning'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/9tzN8sPbyod2dsa0lwuvrwBDWra.jpg'}],
 'Comedy': [{'title': 'The Grand Budapest Hotel',
   'year': 2014,
   'vibes': ['Quirky'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg'},
  {'title': 'Dr. Strangelove',
   'year': 1964,
   'vibes': ['Satirical'],
   'poster_url': ''},
  {'title': 'Monty Python and the Holy Grail',
   'year': 1975,
   'vibes': ['Quirky', 'Satirical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/hWx1ANiWEWWyzKPN0us35HCGnhQ.jpg'},
  {'title': 'Superbad',
   'year': 2007,
   'vibes': ['Light-hearted', 'Feel-good'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg'},
  {'title': 'Bridesmaids',
   'year': 2011,
   'vibes': ['Feel-good', 'Light-hearted'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/gJtA7hYsBMQ7EM3sPBMUdBfU7a0.jpg'},
  {'title': 'Jojo Rabbit',
   'year': 2019,
   'vibes': ['Satirical', 'Quirky'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/1mqL7VG4Ix8wmxwypmCA1HTHBky.jpg'},
  {'title': 'Anchorman: The Legend of Ron Burgundy',
   'year': 2004,
   'vibes': ['Light-hearted'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/mhZIcRePT7U8viFQVjt1ZjYIsR4.jpg'},
  {'title': 'Hot Fuzz',
   'year': 2007,
   'vibes': ['Quirky', 'Satirical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg'},
  {'title': 'Paddington 2',
   'year': 2017,
   'vibes': ['Feel-good', 'Light-hearted'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/1OJ9vkD5xPt3skC6KguyXAgagRZ.jpg'},
  {'title': 'Groundhog Day',
   'year': 1993,
   'vibes': ['Feel-good', 'Light-hearted'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/gCgt1WARPZaXnq523ySQEUKinCs.jpg'}],
 'Crime': [{'title': 'Heat',
   'year': 1995,
   'vibes': ['Gritty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/umSVjVdbVwtx5ryCA2QXL44Durm.jpg'},
  {'title': 'Se7en',
   'year': 1995,
   'vibes': ['Neo-Noir', 'Plot-twisty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg'},
  {'title': 'The Departed',
   'year': 2006,
   'vibes': ['Plot-twisty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg'},
  {'title': 'Chinatown',
   'year': 1974,
   'vibes': ['Slow-burn', 'Neo-Noir'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/kZRSP3FmOcq0xnBulqpUQngJUXY.jpg'},
  {'title': 'City of God',
   'year': 2002,
   'vibes': ['Gritty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg'},
  {'title': 'Memories of Murder',
   'year': 2003,
   'vibes': ['Slow-burn', 'Gritty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/jcgUjx1QcupGzjntTVlnQ15lHqy.jpg'},
  {'title': 'Oldboy',
   'year': 2003,
   'vibes': ['Neo-Noir', 'Plot-twisty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg'},
  {'title': 'The Godfather',
   'year': 1972,
   'vibes': ['Slow-burn'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg'},
  {'title': 'Prisoners',
   'year': 2013,
   'vibes': ['Gritty', 'Plot-twisty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/jsS3a3ep2KyBVmmiwaz3LvK49b1.jpg'},
  {'title': 'The French Connection',
   'year': 1971,
   'vibes': ['Gritty'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/5XSGvIKl2yPvOkieFjc3rzLw7x0.jpg'}],
 'Drama': [{'title': 'Moonlight',
   'year': 2016,
   'vibes': ['Character-driven', 'Emotional'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/rcICfiL9fvwRjoWHxW8QeroLYrJ.jpg'},
  {'title': 'Parasite',
   'year': 2019,
   'vibes': ['Social commentary', 'Character-driven'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'},
  {'title': 'There Will Be Blood',
   'year': 2007,
   'vibes': ['Character-driven', 'Historical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg'},
  {'title': '12 Years a Slave',
   'year': 2013,
   'vibes': ['Historical', 'Emotional'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/xdANQijuNrJaw1HA61rDccME4Tm.jpg'},
  {'title': 'Manchester by the Sea',
   'year': 2016,
   'vibes': ['Emotional', 'Character-driven'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/o9VXYOuaJxCEKOxbA86xqtwmqYn.jpg'},
  {'title': 'Nomadland',
   'year': 2021,
   'vibes': ['Social commentary', 'Emotional'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/8Vc5EOUEIF1EUXuX9eLFf7BvN3P.jpg'},
  {'title': 'The Social Network',
   'year': 2010,
   'vibes': ['Social commentary'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg'},
  {'title': 'A Separation',
   'year': 2011,
   'vibes': ['Emotional', 'Character-driven'],
   'poster_url': ''},
  {'title': "The King's Speech",
   'year': 2010,
   'vibes': ['Historical', 'Emotional'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/pVNKXVQFukBaCz6ML7GH3kiPlQP.jpg'},
  {'title': 'Whiplash',
   'year': 2014,
   'vibes': ['Character-driven', 'Emotional'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg'}],
 'Fantasy': [{'title': "Pan's Labyrinth",
   'year': 2006,
   'vibes': ['Dreamlike', 'Mythic', 'Magical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/s8C4whhKtDaJvMDcyiMvx3BIF5F.jpg'},
  {'title': 'The Lord of the Rings: The Two Towers',
   'year': 2002,
   'vibes': ['High fantasy', 'Mythic'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg'},
  {'title': 'The Green Knight',
   'year': 2021,
   'vibes': ['Mythic', 'Dreamlike'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/if4hw3Ou5Sav9Em7WWHj66mnywp.jpg'},
  {'title': 'Harry Potter and the Prisoner of Azkaban',
   'year': 2004,
   'vibes': ['Magical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg'},
  {'title': "Howl's Moving Castle",
   'year': 2004,
   'vibes': ['Dreamlike', 'Magical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/TkTPELv4kC3u1lkloush8skOjE.jpg'},
  {'title': 'The Shape of Water',
   'year': 2017,
   'vibes': ['Dreamlike', 'Magical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg'},
  {'title': 'Stardust',
   'year': 2007,
   'vibes': ['Magical', 'High fantasy'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/7zbFmxy3DqKYL2M8Hop6uylp2Uy.jpg'},
  {'title': 'Willow',
   'year': 1988,
   'vibes': ['High fantasy'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/pAIRGMIdN7ZdZhflazdV2ezuJ9f.jpg'},
  {'title': 'Big Fish',
   'year': 2003,
   'vibes': ['Dreamlike', 'Magical'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/tjK063yCgaBAluVU72rZ6PKPH2l.jpg'},
  {'title': 'Legend',
   'year': 1985,
   'vibes': ['High fantasy', 'Mythic'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/6n3PQSYpZRK5YPk2w8JEwED7AZk.jpg'}],
 'Horror': [{'title': 'The Exorcist',
   'year': 1973,
   'vibes': ['Supernatural'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/5x0CeVHJI8tcDx8tUUwYHQSNILq.jpg'},
  {'title': 'The Thing',
   'year': 1982,
   'vibes': ['Body horror'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/tzGY49kseSE9QAKk47uuDGwnSCu.jpg'},
  {'title': 'Halloween',
   'year': 1978,
   'vibes': ['Slasher'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/wijlZ3HaYMvlDTPqJoTCWKFkCPU.jpg'},
  {'title': 'Hereditary',
   'year': 2018,
   'vibes': ['Supernatural', 'Twisted'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/4GFPuL14eXi66V96xBWY73Y9PfR.jpg'},
  {'title': 'Get Out',
   'year': 2017,
   'vibes': ['Twisted'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg'},
  {'title': 'A Nightmare on Elm Street',
   'year': 1984,
   'vibes': ['Supernatural', 'Slasher'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/wGTpGGRMZmyFCcrY2YoxVTIBlli.jpg'},
  {'title': 'The Babadook',
   'year': 2014,
   'vibes': ['Supernatural'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/qt3fqapeo94TfvMyld8P7gkpXLz.jpg'},
  {'title': 'It Follows',
   'year': 2015,
   'vibes': ['Supernatural'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/iwnQ1JH1wdWrGYkgWySptJ5284A.jpg'},
  {'title': 'Audition',
   'year': 2000,
   'vibes': ['Twisted', 'Body horror'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/zwGaUMm0wAqi0wkO7LJDlwoA5LP.jpg'},
  {'title': 'The Texas Chain Saw Massacre',
   'year': 1974,
   'vibes': ['Slasher', 'Body horror'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/mpgkRPH1GNkMCgdPk2OMyHzAks7.jpg'}],
 'Romance': [{'title': 'When Harry Met Sally...',
   'year': 1989,
   'vibes': ['Romantic comedy'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/rFOiFUhTMtDetqCGClC9PIgnC1P.jpg'},
  {'title': 'Pride & Prejudice',
   'year': 2005,
   'vibes': ['Heartwarming'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/jnsoq5q98DQaE8yw6WZH0F9dW5G.jpg'},
  {'title': 'The Big Sick',
   'year': 2017,
   'vibes': ['Romantic comedy', 'Heartwarming'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/9fJTT8pBxxQsFILJHTtHhdYFr77.jpg'},
  {'title': 'Before Sunrise',
   'year': 1995,
   'vibes': ['Bittersweet'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg'},
  {'title': 'Call Me by Your Name',
   'year': 2017,
   'vibes': ['Bittersweet'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/gXiE0WveDnT0n5J4sW9TMxXF4oT.jpg'},
  {'title': 'Eternal Sunshine of the Spotless Mind',
   'year': 2004,
   'vibes': ['Bittersweet'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg'},
  {'title': 'Titanic',
   'year': 1997,
   'vibes': ['Tragic love'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg'},
  {'title': 'La La Land',
   'year': 2016,
   'vibes': ['Bittersweet'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg'},
  {'title': 'The Notebook',
   'year': 2004,
   'vibes': ['Tragic love', 'Heartwarming'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg'},
  {'title': 'Notting Hill',
   'year': 1999,
   'vibes': ['Romantic comedy', 'Heartwarming'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/hHRIf2XHeQMbyRb3HUx19SF5Ujw.jpg'}],
 'Science Fiction': [{'title': 'Inception',
   'year': 2010,
   'vibes': ['Mind-bending'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg'},
  {'title': 'The Matrix',
   'year': 1999,
   'vibes': ['Cyberpunk', 'Mind-bending'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/p96dm7sCMn4VYAStA6siNz30G1r.jpg'},
  {'title': 'Blade Runner 2049',
   'year': 2017,
   'vibes': ['Cyberpunk', 'Thought-provoking'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg'},
  {'title': 'Arrival',
   'year': 2016,
   'vibes': ['Thought-provoking'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg'},
  {'title': 'Ex Machina',
   'year': 2015,
   'vibes': ['Thought-provoking'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg'},
  {'title': 'Children of Men',
   'year': 2006,
   'vibes': ['Dystopian', 'Thought-provoking'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/8Xgvmx7WWc7Z9Ws9RAYk7uya2kh.jpg'},
  {'title': 'Annihilation',
   'year': 2018,
   'vibes': ['Mind-bending', 'Thought-provoking'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg'},
  {'title': 'Gattaca',
   'year': 1997,
   'vibes': ['Dystopian', 'Thought-provoking'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/eSKr5Fl1MEC7zpAXaLWBWSBjgJq.jpg'},
  {'title': 'Snowpiercer',
   'year': 2013,
   'vibes': ['Dystopian'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/nzccOvhrLGI0nvAknCEAk8bchD9.jpg'},
  {'title': 'Ghost in the Shell',
   'year': 1995,
   'vibes': ['Cyberpunk', 'Thought-provoking'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/9gC88zYUBARRSThcG93MvW14sqx.jpg'}],
 'Thriller': [{'title': 'The Silence of the Lambs',
   'year': 1991,
   'vibes': ['Psychological', 'Dark'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg'},
  {'title': 'Shutter Island',
   'year': 2010,
   'vibes': ['Psychological', 'Suspenseful'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg'},
  {'title': 'Gone Girl',
   'year': 2014,
   'vibes': ['Psychological', 'Suspenseful'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/ts996lKsxvjkO2yiYG0ht4qAicO.jpg'},
  {'title': 'No Country for Old Men',
   'year': 2007,
   'vibes': ['Intense', 'Dark'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/6d5XOczc226jECq0LIX0siKtgHR.jpg'},
  {'title': 'Nightcrawler',
   'year': 2014,
   'vibes': ['Dark', 'Psychological'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg'},
  {'title': 'The Wages of Fear',
   'year': 1953,
   'vibes': ['Suspenseful', 'Intense'],
   'poster_url': ''},
  {'title': 'Sicario',
   'year': 2015,
   'vibes': ['Intense', 'Suspenseful'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg'},
  {'title': 'The Prestige',
   'year': 2006,
   'vibes': ['Psychological', 'Dark'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/2ZOzyhoW08neG27DVySMCcq2emd.jpg'},
  {'title': 'Buried',
   'year': 2010,
   'vibes': ['Intense', 'Suspenseful'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/splPNB0vAoNlb8l5WYxz2E3FK2G.jpg'},
  {'title': 'The Girl with the Dragon Tattoo',
   'year': 2011,
   'vibes': ['Suspenseful', 'Dark'],
   'poster_url': 'https://image.tmdb.org/t/p/w500/8bokS83zGdhaXgN9tjidUKmAftW.jpg'}]
}


qdrant_client = connect_qdrant(QDRANT_API_KEY, QDRANT_ENDPOINT)


def query_qdrant (filter):
    point, _ = qdrant_client.scroll(
        collection_name=QDRANT_MOVIE_COLLECTION_NAME,
        scroll_filter=filter,
        limit=1,
        with_payload=True,
        with_vectors=False,
    )
    return point


for genre, medias in SEED_MOVIES.items():
    for m in medias:
        filter = build_qfilter(titles=[m['title']], release_year=m['year'])
        print (m['title'])
        point = query_qdrant(filter)
        if point:
            payload = point[0].payload
            # print (payload['poster_url'])
            # print (payload['media_id'])
            # m['poster_url'] = payload['poster_url']
            # m['media_id'] = payload['poster_url']
