from reelix_core.config import (
    QDRANT_API_KEY,
    QDRANT_ENDPOINT,
    QDRANT_MOVIE_COLLECTION_NAME,
)
from reelix_retrieval.filter_builder import build_qfilter
from reelix_retrieval.vectorstore import connect_qdrant

SEEDS_300 = {
    "Action": [
        {
            "title": "Mad Max: Fury Road",
            "year": 2015,
            "vibes": ["Dystopian", "Post-Apocalyptic", "Dieselpunk"],
        },
        {
            "title": "John Wick",
            "year": 2014,
            "vibes": ["Action Thriller", "Revenge", "Action-Packed"],
        },
        {
            "title": "Mission: Impossible - Fallout",
            "year": 2018,
            "vibes": ["Espionage", "High-Stakes", "Fast-Paced"],
        },
        {"title": "Skyfall", "year": 2012, "vibes": ["Espionage", "High-stakes"]},
        {
            "title": "Crouching Tiger, Hidden Dragon",
            "year": 2000,
            "vibes": ["Action epic", "Martial Arts"],
        },
        {"title": "Die Hard", "year": 1988, "vibes": ["High-stakes", "Action-packed"]},
        {
            "title": "Gladiator",
            "year": 2000,
            "vibes": ["Action epic", "Grand journey", "Sword and Sandal"],
        },
        {
            "title": "The Bourne Ultimatum",
            "year": 2007,
            "vibes": ["Espionage", "Fast-paced"],
        },
        {
            "title": "Edge of Tomorrow",
            "year": 2014,
            "vibes": ["Fast-paced", "Action-packed"],
        },
        {
            "title": "The Dark Knight",
            "year": 2008,
            "vibes": ["High-stakes", "Action-packed"],
        },
        {
            "title": "Casino Royale",
            "year": 2006,
            "vibes": ["Espionage", "High-stakes", "Reboot"],
        },
        {
            "title": "Top Gun: Maverick",
            "year": 2022,
            "vibes": ["High-octane", "Nostalgic", "Spectacular"],
        },
        {
            "title": "The Northman",
            "year": 2022,
            "vibes": ["Historical Epic", "Mythic", "Gritty"],
        },
        {
            "title": "Terminator 2: Judgment Day",
            "year": 1991,
            "vibes": ["Sci-fi action", "High-stakes"],
        },
        {
            "title": "Heat",
            "year": 1995,
            "vibes": ["Crime action", "Methodical", "Epic"],
        },
        {
            "title": "Wonder Woman",
            "year": 2017,
            "vibes": ["Superhero", "Empowering", "Period setting"],
        },
        {
            "title": "Dawn of the Planet of the Apes",
            "year": 2014,
            "vibes": ["Intense", "Dystopian", "Thought-provoking"],
        },
        {
            "title": "The Matrix",
            "year": 1999,
            "vibes": ["Sci-fi action", "Mind-bending", "Revolutionary"],
        },
        {
            "title": "Face/Off",
            "year": 1997,
            "vibes": ["Over-the-top", "High-concept", "Explosive"],
        },
        {
            "title": "Speed",
            "year": 1994,
            "vibes": ["High-concept thriller", "Non-stop action"],
        },
        # {'title': 'Aliens', 'year': 1986, 'vibes': ['Sci-fi action', 'Military', 'Intense']},
        {
            "title": "Kill Bill: Vol. 1",
            "year": 2003,
            "vibes": ["Stylized violence", "Revenge", "Martial arts"],
        },
        {
            "title": "The Rock",
            "year": 1996,
            "vibes": ["Blockbuster", "High-stakes", "Island setting"],
        },
        # {'title': 'Logan', 'year': 2017, 'vibes': ['Dystopian', 'Neo-Western', 'Character-Driven']},
        {
            "title": "John Wick: Chapter 4",
            "year": 2023,
            "vibes": ["Stylized Action", "Revenge", "Modern"],
        },
        {
            "title": "Blood Diamond",
            "year": 2006,
            "vibes": ["Action Epic", "Political Thriller", "Emotional"],
        },
        {
            "title": "Atomic Blonde",
            "year": 2017,
            "vibes": ["Stylish", "Espionage", "Female-led"],
        },
        {
            "title": "The Equalizer",
            "year": 2014,
            "vibes": ["Vigilante Justice", "Methodical", "Modern"],
        },
        {
            "title": "Nobody",
            "year": 2021,
            "vibes": ["Suburban Dad Action", "Dark Comedy", "Cathartic"],
        },
        {
            "title": "Extraction",
            "year": 2020,
            "vibes": ["Military action", "International", "Gritty"],
        },
    ],
    "Adventure": [
        {
            "title": "Raiders of the Lost Ark",
            "year": 1981,
            "vibes": ["Epic scale", "Grand journey"],
        },
        {
            "title": "The Lord of the Rings: The Fellowship of the Ring",
            "year": 2001,
            "vibes": ["Swashbuckler", "Grand journey", "Euphoric"],
        },
        {
            "title": "Spirited Away",
            "year": 2001,
            "vibes": ["Whimsical", "Visually-stunning"],
        },
        {
            "title": "Pirates of the Caribbean: The Curse of the Black Pearl",
            "year": 2003,
            "vibes": ["Whimsical", "Visually-stunning"],
        },
        {
            "title": "Into the Wild",
            "year": 2007,
            "vibes": ["Philosophical", "Poignant", "Somber"],
        },
        {
            "title": "Life of Pi",
            "year": 2012,
            "vibes": ["Visually-stunning", "Grand journey"],
        },
        {"title": "Up", "year": 2009, "vibes": ["Whimsical", "Grand journey"]},
        {
            "title": "Avengers: Endgame",
            "year": 2019,
            "vibes": ["Epic scale", "Visually-stunning"],
        },
        {
            "title": "The Revenant",
            "year": 2015,
            "vibes": ["Grand journey", "Epic scale"],
        },
        {
            "title": "The Secret Life of Walter Mitty",
            "year": 2013,
            "vibes": ["Whimsical", "Grand Journey"],
        },
        {
            "title": "Moana",
            "year": 2016,
            "vibes": ["Grand journey", "Visually-stunning"],
        },
        {
            "title": "Indiana Jones and the Last Crusade",
            "year": 1989,
            "vibes": ["Classic Adventure", "Father-son dynamic"],
        },
        {
            "title": "The Princess Bride",
            "year": 1987,
            "vibes": ["Fairy tale", "Swashbuckler", "Quotable"],
        },
        {
            "title": "Jurassic Park",
            "year": 1993,
            "vibes": ["Monster Adventure", "Groundbreaking Effects"],
        },
        {
            "title": "The Mummy",
            "year": 1999,
            "vibes": ["Pulp adventure", "Horror-comedy", "Treasure hunt"],
        },
        {
            "title": "National Treasure",
            "year": 2004,
            "vibes": ["Modern treasure hunt", "Puzzle-solving"],
        },
        {
            "title": "The Jungle Book",
            "year": 2016,
            "vibes": ["Coming-of-age", "Nature adventure"],
        },
        {
            "title": "Finding Nemo",
            "year": 2003,
            "vibes": ["Underwater adventure", "Father-son journey"],
        },
        {
            "title": "Interstellar",
            "year": 2014,
            "vibes": ["Adventure Epic", "Time Travel", "Emotional"],
        },
        # {'title': 'Stand by Me', 'year': 1986, 'vibes': ['Coming-of-age journey', 'Friendship']},
        {
            "title": "Lawrence of Arabia",
            "year": 1962,
            "vibes": ["Epic desert adventure", "Historical"],
        },
        {
            "title": "The Wild Robot",
            "year": 2024,
            "vibes": ["Animal Adventure", "Heartwarming", "Introspective"],
        },
        {
            "title": "Tomb Raider",
            "year": 2018,
            "vibes": ["Modern Adventure", "Female Protagonist"],
        },
        {
            "title": "Jumanji: Welcome to the Jungle",
            "year": 2017,
            "vibes": ["Video game adventure", "Comedy"],
        },
        {
            "title": "The Lion King",
            "year": 1994,
            "vibes": ["Adventure epic", "Coming-of-Age", "Family"],
        },
        {
            "title": "Sherlock Holmes",
            "year": 2009,
            "vibes": ["Action Adventure", "Mystery", "Witty"],
        },
        {
            "title": "Jungle Cruise",
            "year": 2021,
            "vibes": ["Theme park adventure", "Comedy"],
        },
        {
            "title": "The Way Back",
            "year": 2010,
            "vibes": ["Survival epic", "Historical journey"],
        },
        {
            "title": "Wild",
            "year": 2014,
            "vibes": ["Personal journey", "Memoir adaptation"],
        },
        {
            "title": "King Kong",
            "year": 2005,
            "vibes": ["Adventure Epic", "Jungle adventure", "Tragic"],
        },
    ],
    "Comedy": [
        {
            "title": "The Grand Budapest Hotel",
            "year": 2014,
            "vibes": ["Quirky", "Melancholic"],
        },
        {"title": "Green Book", "year": 2018, "vibes": ["Feel-Good", "Period Drama"]},
        {
            "title": "Poor Things",
            "year": 2023,
            "vibes": ["Absurd", "Gothic", "Dark Comedy"],
        },
        {"title": "Zombieland", "year": 2009, "vibes": ["Light-Hearted", "Satirical"]},
        {
            "title": "Mean Girls",
            "year": 2004,
            "vibes": ["Coming-of-age", "Light-hearted", "Teen Comedy"],
        },
        {"title": "Jojo Rabbit", "year": 2019, "vibes": ["Satirical", "Quirky"]},
        {
            "title": "Anchorman: The Legend of Ron Burgundy",
            "year": 2004,
            "vibes": ["Light-hearted", "Absurd"],
        },
        {"title": "Hot Fuzz", "year": 2007, "vibes": ["Quirky", "Satirical"]},
        {
            "title": "Paddington 2",
            "year": 2017,
            "vibes": ["Feel-good", "Light-hearted", "Family"],
        },
        {
            "title": "The Big Lebowski",
            "year": 1998,
            "vibes": ["Absurd", "Satirical", "Neo-Noir"],
        },
        {
            "title": "Superbad",
            "year": 2007,
            "vibes": ["Coming-of-age", "Raunchy", "Friendship"],
        },
        {
            "title": "Bridesmaids",
            "year": 2011,
            "vibes": ["Female-driven", "Raunchy", "Wedding Comedy"],
        },
        {
            "title": "The Hangover",
            "year": 2009,
            "vibes": ["Bachelor party", "Mystery Comedy", "Raunchy"],
        },
        {
            "title": "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
            "year": 2006,
            "vibes": ["Mockumentary", "Satirical", "Controversial"],
        },
        {
            "title": "Tropic Thunder",
            "year": 2008,
            "vibes": ["Hollywood satire", "Action comedy"],
        },
        {
            "title": "21 Jump Street",
            "year": 2012,
            "vibes": ["Buddy Comedy", "Action Comedy"],
        },
        {
            "title": "Knives Out",
            "year": 2019,
            "vibes": ["Murder mystery", "Ensemble", "Witty"],
        },
        {
            "title": "Game Night",
            "year": 2018,
            "vibes": ["Dark comedy", "Thriller comedy"],
        },
        {"title": "Snatch", "year": 2000, "vibes": ["Dark Comedy", "Caper", "Witty"]},
        {
            "title": "Hunt for the Wilderpeople",
            "year": 2016,
            "vibes": ["New Zealand comedy", "Adventure"],
        },
        {
            "title": "In Bruges",
            "year": 2008,
            "vibes": ["Dark comedy", "Crime comedy", "Philosophical"],
        },
        # {'title': 'Kiss Kiss Bang Bang', 'year': 2005, 'vibes': ['Neo-noir comedy', 'Shane Black']},
        {
            "title": "The Nice Guys",
            "year": 2016,
            "vibes": ["Buddy comedy", "70s setting", "Crime"],
        },
        {
            "title": "Thor: Ragnarok",
            "year": 2017,
            "vibes": ["Superhero comedy", "Space adventure"],
        },
        {
            "title": "Deadpool",
            "year": 2016,
            "vibes": ["Superhero parody", "Meta-humor", "R-rated"],
        },
        {
            "title": "Booksmart",
            "year": 2019,
            "vibes": ["Coming-of-age", "Female friendship", "Smart"],
        },
        {
            "title": "The Other Guys",
            "year": 2010,
            "vibes": ["Buddy cops", "Will Ferrell", "Satirical"],
        },
        {
            "title": "Step Brothers",
            "year": 2008,
            "vibes": ["Absurd", "Family comedy", "Childish humor"],
        },
        {
            "title": "Pineapple Express",
            "year": 2008,
            "vibes": ["Stoner comedy", "Action comedy"],
        },
        {
            "title": "Little Miss Sunshine",
            "year": 2006,
            "vibes": ["Coming-of-Age", "Road Trip", "Offbeat"],
        },
    ],
    "Crime": [
        {"title": "Heat", "year": 1995, "vibes": ["Gritty"]},
        {"title": "Se7en", "year": 1995, "vibes": ["Neo-Noir", "Plot-twisty"]},
        {"title": "The Departed", "year": 2006, "vibes": ["Plot-twisty"]},
        {"title": "Chinatown", "year": 1974, "vibes": ["Slow-burn", "Neo-Noir"]},
        {"title": "City of God", "year": 2002, "vibes": ["Gritty"]},
        {"title": "Memories of Murder", "year": 2003, "vibes": ["Slow-burn", "Gritty"]},
        {"title": "Oldboy", "year": 2003, "vibes": ["Neo-Noir", "Plot-twisty"]},
        {
            "title": "The Gentlemen",
            "year": 2020,
            "vibes": ["Fast-paced", "Dark comedy"],
        },
        {"title": "The Godfather", "year": 1972, "vibes": ["Slow-burn"]},
        {"title": "Prisoners", "year": 2013, "vibes": ["Gritty", "Plot-twisty"]},
        {
            "title": "Pulp Fiction",
            "year": 1994,
            "vibes": ["Satirical", "Non-linear narrative"],
        },
        {
            "title": "GoodFellas",
            "year": 1990,
            "vibes": ["Crime epic", "Darkly funny", "Rise and fall"],
        },
        {
            "title": "The Godfather Part II",
            "year": 1974,
            "vibes": ["Epic sequel", "Multi-generational"],
        },
        {
            "title": "Casino",
            "year": 1995,
            "vibes": ["Las Vegas crime", "Epic scope", "Scorsese"],
        },
        {
            "title": "Scarface",
            "year": 1983,
            "vibes": ["Rise and fall", "Excess", "Iconic"],
        },
        {
            "title": "Léon: The Professional",
            "year": 1994,
            "vibes": ["Action Thriller", "Neo-Noir", "Somber"],
        },
        {
            "title": "Miller's Crossing",
            "year": 1990,
            "vibes": ["Prohibition era", "Coen Brothers"],
        },
        {
            "title": "L.A. Confidential",
            "year": 1997,
            "vibes": ["Neo-noir", "1950s Los Angeles"],
        },
        {
            "title": "The Usual Suspects",
            "year": 1995,
            "vibes": ["Caper", "Plot-twisty", "Neo-Noir"],
        },
        {
            "title": "Donnie Brasco",
            "year": 1997,
            "vibes": ["Undercover", "Mafia infiltration"],
        },
        {
            "title": "Training Day",
            "year": 2001,
            "vibes": ["Cop Drama", "Denzel Washington", "Police Procedural"],
        },
        {
            "title": "Collateral",
            "year": 2004,
            "vibes": ["Night in LA", "Hitman thriller"],
        },
        {
            "title": "Baby Driver",
            "year": 2017,
            "vibes": ["Music-driven", "Stylish", "Heist"],
        },
        {
            "title": "Hell or High Water",
            "year": 2016,
            "vibes": ["Modern western", "Bank robbery"],
        },
        {
            "title": "Wind River",
            "year": 2017,
            "vibes": ["Murder mystery", "Neo-western", "Snow"],
        },
        {
            "title": "The Town",
            "year": 2010,
            "vibes": ["Boston crime", "Bank robbery", "Ben Affleck"],
        },
        {
            "title": "Gone Baby Gone",
            "year": 2007,
            "vibes": ["Missing child", "Boston setting"],
        },
        {
            "title": "Zodiac",
            "year": 2007,
            "vibes": ["Serial killer investigation", "70s period"],
        },
        {
            "title": "The Irishman",
            "year": 2019,
            "vibes": ["Crime epic", "Aging gangsters", "Scorsese"],
        },
        {
            "title": "Knives Out",
            "year": 2019,
            "vibes": ["Murder mystery", "Ensemble", "Modern whodunit"],
        },
        {
            "title": "The Hateful Eight",
            "year": 2015,
            "vibes": ["Suspense Mystery", "Gritty", "Intense"],
        },
        {
            "title": "Mystic River",
            "year": 2003,
            "vibes": ["Neo-noir", "Mystery", "Somber"],
        },
    ],
    "Drama": [
        {
            "title": "Moonlight",
            "year": 2016,
            "vibes": ["Character-driven", "Emotional"],
        },
        {
            "title": "Parasite",
            "year": 2019,
            "vibes": ["Social commentary", "Character-driven", "Class warfare"],
        },
        {
            "title": "There Will Be Blood",
            "year": 2007,
            "vibes": ["Character-driven", "Historical"],
        },
        {
            "title": "12 Years a Slave",
            "year": 2013,
            "vibes": ["Historical", "Emotional"],
        },
        {
            "title": "Manchester by the Sea",
            "year": 2016,
            "vibes": ["Emotional", "Character-driven"],
        },
        {
            "title": "Nomadland",
            "year": 2021,
            "vibes": ["Social Commentary", "Freedom", "Reflective"],
        },
        {
            "title": "The Social Network",
            "year": 2010,
            "vibes": ["Docudrama", "Social Commentary", "Biography"],
        },
        {
            "title": "Ford v Ferrari",
            "year": 2019,
            "vibes": ["Docudrama", "Period drama"],
        },
        {
            "title": "The King's Speech",
            "year": 2010,
            "vibes": ["Historical", "Emotional", "Biography"],
        },
        {"title": "Whiplash", "year": 2014, "vibes": ["Character-driven", "Emotional"]},
        {
            "title": "Birdman or (The Unexpected Virtue of Ignorance)",
            "year": 2014,
            "vibes": ["Meta-theatrical", "Character study", "Long takes"],
        },
        {
            "title": "Spotlight",
            "year": 2015,
            "vibes": ["Investigative Journalism", "Social Issue Drama", "True Story"],
        },
        {
            "title": "Room",
            "year": 2015,
            "vibes": ["Psychological", "Mother-Child"],
        },
        {
            "title": "Call Me by Your Name",
            "year": 2017,
            "vibes": ["Coming-of-Age", "Steamy", "Summer Romance"],
        },
        {
            "title": "Lady Bird",
            "year": 2017,
            "vibes": ["Coming-of-Age", "Mother-Daughter", "Heartfelt"],
        },
        {
            "title": "Three Billboards Outside Ebbing, Missouri",
            "year": 2017,
            "vibes": ["Dark comedy-drama", "Small town"],
        },
        {
            "title": "The Big Short",
            "year": 2015,
            "vibes": ["Biography", "Dark comedy", "Docudrama"],
        },
        {
            "title": "Green Book",
            "year": 2018,
            "vibes": ["Racial relations", "Road trip", "1960s"],
        },
        {
            "title": "First Man",
            "year": 2018,
            "vibes": ["Historical Drama", "Biography", "Tragic"],
        },
        {
            "title": "A Star Is Born",
            "year": 2018,
            "vibes": ["Music Industry", "Addiction", "Romance"],
        },
        {
            "title": "Marriage Story",
            "year": 2019,
            "vibes": ["Divorce", "Domestic Drama", "Melancholic"],
        },
        {
            "title": "1917",
            "year": 2019,
            "vibes": ["WWI", "Single-Shot Style", "Gritty"],
        },
        {
            "title": "Conclave",
            "year": 2024,
            "vibes": ["Papal", "Political Drama", "Character-Driven"],
        },
        {
            "title": "Anora",
            "year": 2024,
            "vibes": ["Dark Comedy", "Poignant", "Neorealism"],
        },
        {
            "title": "The Father",
            "year": 2020,
            "vibes": ["Dementia", "Anthony Hopkins", "Perspective"],
        },
        {
            "title": "CODA",
            "year": 2021,
            "vibes": ["Deaf family", "Coming-of-age", "Music"],
        },
        {
            "title": "Bohemian Rhapsody",
            "year": 2018,
            "vibes": ["Docudrama", "Biography", "Melodramatic"],
        },
        {
            "title": "Oppenheimer",
            "year": 2023,
            "vibes": ["Historical Epic", "Psychological", "Character Study"],
        },
        {
            "title": "TÁR",
            "year": 2022,
            "vibes": ["Classical Music", "Power Dynamics", "Psychological Drama"],
        },
        {
            "title": "Million Dollar Baby",
            "year": 2004,
            "vibes": ["Sports Drama", "Emotional", "Boxing"],
        },
        # {
        #     "title": "Drive My Car",
        #     "year": 2021,
        #     "vibes": ["Road Movie", "Slow-Burn", "Grief and Loss"],
        # },
    ],
    "Fantasy": [
        {
            "title": "Pan's Labyrinth",
            "year": 2006,
            "vibes": ["Dreamlike", "Mythic", "Magical"],
        },
        {
            "title": "The Lord of the Rings: The Two Towers",
            "year": 2002,
            "vibes": ["High fantasy", "Mythic"],
        },
        {
            "title": "Harry Potter and the Prisoner of Azkaban",
            "year": 2004,
            "vibes": ["Magical"],
        },
        {
            "title": "Howl's Moving Castle",
            "year": 2004,
            "vibes": ["Dreamlike", "Magical"],
        },
        {
            "title": "The Shape of Water",
            "year": 2017,
            "vibes": ["Fantasy Romance", "Dreamlike", "Magical"],
        },
        {"title": "Stardust", "year": 2007, "vibes": ["Magical", "High Fantasy"]},
        {
            "title": "The Curious Case of Benjamin Button",
            "year": 2008,
            "vibes": ["Period Piece", "Whimsical", "Melancholic"],
        },
        {"title": "Big Fish", "year": 2003, "vibes": ["Dreamlike", "Magical"]},
        {
            "title": "Avatar",
            "year": 2009,
            "vibes": ["Fantasy Epic", "Mythic", "Reverent"],
        },
        {
            "title": "The Lord of the Rings: The Return of the King",
            "year": 2003,
            "vibes": ["Epic conclusion", "Mythic"],
        },
        {
            "title": "Harry Potter and the Goblet of Fire",
            "year": 2005,
            "vibes": ["Tournament", "Darker tone"],
        },
        {
            "title": "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
            "year": 2005,
            "vibes": ["Children's Fantasy", "Christian Allegory"],
        },
        {
            "title": "Fantastic Beasts and Where to Find Them",
            "year": 2016,
            "vibes": ["Wizarding World", "Nostalgia", "Magical"],
        },
        {
            "title": "The Green Knight",
            "year": 2021,
            "vibes": ["Arthurian Legend", "A24", "Medieval"],
        },
        {
            "title": "The Lighthouse",
            "year": 2019,
            "vibes": ["Psychological Fantasy", "Black and white"],
        },
        {
            "title": "Barbie",
            "year": 2023,
            "vibes": ["Musical Fantasy", "High-Concept Comedy", "Satirical"],
        },
        {
            "title": "The Golden Compass",
            "year": 2007,
            "vibes": ["Parallel Worlds", "Young Adult"],
        },
        {
            "title": "Percy Jackson & the Olympians: The Lightning Thief",
            "year": 2010,
            "vibes": ["Greek Mythology", "Young Adult"],
        },
        {
            "title": "The Spiderwick Chronicles",
            "year": 2008,
            "vibes": ["Children's Fantasy", "Fairy creatures"],
        },
        {
            "title": "Spider-Man: Into the Spider-Verse",
            "year": 2018,
            "vibes": ["Teen Adventure", "Quirky", "Imaginative"],
        },
        {
            "title": "Interview with the Vampire",
            "year": 1994,
            "vibes": ["Dark Fantasy", "Gothic Horror", "Vampire"],
        },
        {
            "title": "Okja",
            "year": 2017,
            "vibes": ["Dystopian", "Heartwarming", "Satirical"],
        },
        {
            "title": "The Hunger Games",
            "year": 2012,
            "vibes": ["Dystopian", "Teen Adventure", "Survival"],
        },
        {
            "title": "Wicked",
            "year": 2024,
            "vibes": ["Pop Musical", "Vibrant", "Emotional"],
        },
        {
            "title": "Legend",
            "year": 1985,
            "vibes": ["Ridley Scott", "Tim Curry", "Dark fantasy"],
        },
        {
            "title": "Beauty and the Beast",
            "year": 2017,
            "vibes": ["Romantic Fantasy", "Fairy-Tale", "Musical"],
        },
        {
            "title": "Edward Scissorhands",
            "year": 1990,
            "vibes": ["Dark Fantasy", "Gothic Romance", "Tragic"],
        },
        {
            "title": "Hugo",
            "year": 2011,
            "vibes": ["Period drama", "Whimsical magic", "Heartfelt"],
        },
        {
            "title": "My Neighbor Totoro",
            "year": 1988,
            "vibes": ["Magical realism", "Nostalgia", "Heartwarming"],
        },
        {
            "title": "300",
            "year": 2007,
            "vibes": ["Action epic", "Mythic", "Sword and Sandal"],
        },
    ],
    "Horror": [
        {"title": "Alien", "year": 1979, "vibes": ["Space Opera", "Monster Horror"]},
        {"title": "The Substance", "year": 2024, "vibes": ["Body Horror", "Sardonic"]},
        {
            "title": "American Psycho",
            "year": 2000,
            "vibes": ["Slasher", "Psychological"],
        },
        {"title": "Hereditary", "year": 2018, "vibes": ["Supernatural", "Twisted"]},
        {"title": "Get Out", "year": 2017, "vibes": ["Twisted", "Social Commentary"]},
        {
            "title": "A Nightmare on Elm Street",
            "year": 1984,
            "vibes": ["Supernatural", "Slasher"],
        },
        {"title": "Midsommar", "year": 2019, "vibes": ["Supernatural", "Folk horror"]},
        {
            "title": "It",
            "year": 2017,
            "vibes": ["Supernatural", "Suspenseful", "Coming-of-Age"],
        },
        {
            "title": "A Quiet Place",
            "year": 2018,
            "vibes": ["Survival", "Monster Horror"],
        },
        {"title": "Split", "year": 2017, "vibes": ["Suspenseful", "Claustrophobic"]},
        {
            "title": "Nosferatu",
            "year": 2024,
            "vibes": ["Gothic Horror", "Supernatural", "Vampire"],
        },
        {
            "title": "Halloween",
            "year": 1978,
            "vibes": ["Slasher", "Michael Myers", "Suspense"],
        },
        {
            "title": "The Lighthouse",
            "year": 2019,
            "vibes": ["Folk Horror", "Claustrophobic", "Character Study"],
        },
        {
            "title": "Psycho",
            "year": 1960,
            "vibes": ["Hitchcock", "Shower scene", "Twist ending"],
        },
        {
            "title": "The Shining",
            "year": 1980,
            "vibes": ["Kubrick", "Hotel Isolation", "Madness"],
        },
        {
            "title": "Jaws",
            "year": 1975,
            "vibes": ["Monster Horror", "Ominous", "Survival"],
        },
        {
            "title": "The Babadook",
            "year": 2014,
            "vibes": ["Psychological", "Grief metaphor", "Australian"],
        },
        {
            "title": "The Conjuring",
            "year": 2013,
            "vibes": ["Supernatural", "Paranormal investigators"],
        },
        {
            "title": "Sinister",
            "year": 2012,
            "vibes": ["Found footage elements", "Writer protagonist"],
        },
        # {'title': 'Insidious', 'year': 2010, 'vibes': ['Astral projection', 'Family horror']},
        {
            "title": "The Ring",
            "year": 2002,
            "vibes": ["J-horror remake", "Cursed videotape"],
        },
        {
            "title": "Scream",
            "year": 1996,
            "vibes": ["Meta-horror", "Slasher revival", "Wes Craven"],
        },
        {
            "title": "Saw",
            "year": 2004,
            "vibes": ["Torture Porn", "Puzzle Traps", "Low Budget"],
        },
        {
            "title": "The Blair Witch Project",
            "year": 1999,
            "vibes": ["Found Footage", "Marketing Phenomenon"],
        },
        {
            "title": "Paranormal Activity",
            "year": 2007,
            "vibes": ["Found footage", "Suburban setting"],
        },
        {
            "title": "The Witch",
            "year": 2016,
            "vibes": ["Period horror", "Puritan family", "Folklore"],
        },
        {
            "title": "It Follows",
            "year": 2015,
            "vibes": ["STD metaphor", "Retro aesthetic", "Unique premise"],
        },
        {
            "title": "Train to Busan",
            "year": 2016,
            "vibes": ["Zombie thriller", "Korean", "Emotional"],
        },
        {
            "title": "The Descent",
            "year": 2005,
            "vibes": ["Claustrophobic", "Cave exploration", "Creatures"],
        },
        {
            "title": "28 Days Later",
            "year": 2002,
            "vibes": ["Zombie apocalypse", "Fast zombies", "Post-9/11"],
        },
    ],
    "Romance": [
        {
            "title": "When Harry Met Sally...",
            "year": 1989,
            "vibes": ["Romantic comedy"],
        },
        {
            "title": "Pride & Prejudice",
            "year": 2005,
            "vibes": ["Heartwarming", "Period drama"],
        },
        {
            "title": "The Big Sick",
            "year": 2017,
            "vibes": ["Romantic comedy", "Heartwarming"],
        },
        {"title": "Before Sunrise", "year": 1995, "vibes": ["Bittersweet"]},
        {"title": "Call Me by Your Name", "year": 2017, "vibes": ["Bittersweet"]},
        {
            "title": "Eternal Sunshine of the Spotless Mind",
            "year": 2004,
            "vibes": ["Bittersweet"],
        },
        {"title": "Titanic", "year": 1997, "vibes": ["Tragic love"]},
        {
            "title": "La La Land",
            "year": 2016,
            "vibes": ["Bittersweet", "Visually-stunning"],
        },
        {
            "title": "The Notebook",
            "year": 2004,
            "vibes": ["Tragic love", "Heartwarming"],
        },
        {
            "title": "Midnight in Paris",
            "year": 2011,
            "vibes": ["Nostalgic", "Metaphorical", "Romantic comedy"],
        },
        {
            "title": "Notting Hill",
            "year": 1999,
            "vibes": ["Romantic comedy", "Heartwarming"],
        },
        {
            "title": "The Handmaiden",
            "year": 2016,
            "vibes": ["Dark romance", "Erotic thriller", "Steamy romance"],
        },
        {
            "title": "Begin Again",
            "year": 2014,
            "vibes": ["Musical Drama", "Second Chances", "Feel-good"],
        },
        {
            "title": "Sleepless in Seattle",
            "year": 1993,
            "vibes": ["Destined love", "Cross-country romance"],
        },
        {
            "title": "You've Got Mail",
            "year": 1998,
            "vibes": ["Email romance", "Small business vs corporate"],
        },
        {
            "title": "Pretty Woman",
            "year": 1990,
            "vibes": ["Modern fairy tale", "Class differences"],
        },
        {
            "title": "Ghost",
            "year": 1990,
            "vibes": ["Supernatural romance", "Patrick Swayze", "Pottery scene"],
        },
        {
            "title": "Brokeback Mountain",
            "year": 2005,
            "vibes": ["Neo-Western", "Melancholic", "Steamy Romance"],
        },
        {
            "title": "Up in the Air",
            "year": 2009,
            "vibes": ["Workplace Drama", "Witty", "Tragic Romance"],
        },
        {
            "title": "Past Lives",
            "year": 2023,
            "vibes": ["Indie Drama", "Anti-Fairy Tale", "Bittersweet"],
        },
        {
            "title": "Before Sunset",
            "year": 2004,
            "vibes": ["Sequel", "Paris setting", "Real-time conversation"],
        },
        {
            "title": "The Great Gatsby",
            "year": 2013,
            "vibes": ["Period Drama", "Tragic Romance", "Dreamlike"],
        },
        {
            "title": "(500) Days of Summer",
            "year": 2009,
            "vibes": ["Anti-romantic comedy", "Expectations vs reality"],
        },
        {
            "title": "Silver Linings Playbook",
            "year": 2012,
            "vibes": ["Romantic Comedy", "Heartfelt", "Bittersweet"],
        },
        {
            "title": "Lost in Translation",
            "year": 2003,
            "vibes": ["Cross-cultural", "Tokyo", "Age gap friendship"],
        },
        {
            "title": "Amélie",
            "year": 2001,
            "vibes": ["French romance", "Whimsical", "Paris", "Color palette"],
        },
        # {'title': 'The Shape of Water', 'year': 2017, 'vibes': ['Interspecies romance', 'Cold War', 'Guillermo del Toro']},
        {
            "title": "Carol",
            "year": 2015,
            "vibes": ["1950s lesbian romance", "Cate Blanchett", "Period piece"],
        },
        {
            "title": "Moonrise Kingdom",
            "year": 2012,
            "vibes": ["Young love", "Wes Anderson", "Summer camp"],
        },
        {
            "title": "About Time",
            "year": 2013,
            "vibes": ["Time travel romance", "Family relationships", "British"],
        },
    ],
    "Science Fiction": [
        {
            "title": "Inception",
            "year": 2010,
            "vibes": ["Mind-bending", "Cerebral", "Psychological"],
        },
        {"title": "The Matrix", "year": 1999, "vibes": ["Cyberpunk", "Mind-bending"]},
        {
            "title": "Blade Runner 2049",
            "year": 2017,
            "vibes": ["Cyberpunk", "Thought-provoking", "Dystopian"],
        },
        {"title": "Arrival", "year": 2016, "vibes": ["Thought-provoking"]},
        {"title": "Ex Machina", "year": 2015, "vibes": ["Thought-provoking"]},
        {
            "title": "Children of Men",
            "year": 2006,
            "vibes": ["Dystopian", "Thought-provoking"],
        },
        {
            "title": "Everything Everywhere All at Once",
            "year": 2022,
            "vibes": ["Quirky", "Existential", "Mind-bending"],
        },
        {"title": "Gattaca", "year": 1997, "vibes": ["Dystopian", "Thought-provoking"]},
        {
            "title": "Gravity",
            "year": 2013,
            "vibes": ["Claustrophobic", "Visually Stunning", "Tense"],
        },
        {"title": "Her", "year": 2013, "vibes": ["Poignant", "Thought-provoking"]},
        {
            "title": "Ghost in the Shell",
            "year": 1995,
            "vibes": ["Cyberpunk", "Thought-provoking"],
        },
        {
            "title": "Blade Runner",
            "year": 1982,
            "vibes": ["Neo-noir sci-fi", "Replicants", "Philip K. Dick"],
        },
        {
            "title": "2001: A Space Odyssey",
            "year": 1968,
            "vibes": ["Kubrick", "HAL 9000", "Evolution"],
        },
        {
            "title": "Star Wars",
            "year": 1977,
            "vibes": ["Space opera", "Hero's journey"],
        },
        {
            "title": "E.T. the Extra-Terrestrial",
            "year": 1982,
            "vibes": ["Family sci-fi", "Spielberg", "Friendship"],
        },
        {
            "title": "Logan",
            "year": 2017,
            "vibes": ["Dystopian", "Neo-Western", "Character-Driven"],
        },
        {
            "title": "Terminator 2: Judgment Day",
            "year": 1991,
            "vibes": ["Time travel", "AI apocalypse", "Action"],
        },
        {
            "title": "Back to the Future",
            "year": 1985,
            "vibes": ["Time travel", "Comedy", "Family-friendly"],
        },
        {
            "title": "Star Trek",
            "year": 2009,
            "vibes": ["Space Adventure", "Time Travel", " Fast-Paced"],
        },
        {
            "title": "V for Vendetta",
            "year": 2006,
            "vibes": ["Distopian Sci-Fi", "Cold War", "Political Drama"],
        },
        {
            "title": "Ghostbusters",
            "year": 1984,
            "vibes": ["Supernatural", "Quirky", "Deadpan Humor"],
        },
        {
            "title": "District 9",
            "year": 2009,
            "vibes": ["Apartheid allegory", "South African", "Found footage"],
        },
        {
            "title": "Moon",
            "year": 2009,
            "vibes": ["Isolation", "AI companion", "Sam Rockwell"],
        },
        {
            "title": "Primer",
            "year": 2004,
            "vibes": ["Low-budget", "Complex time travel", "Engineers"],
        },
        {
            "title": "Looper",
            "year": 2012,
            "vibes": ["Time travel assassins", "Joseph Gordon-Levitt"],
        },
        {
            "title": "Minority Report",
            "year": 2002,
            "vibes": ["Pre-crime", "Philip K. Dick", "Spielberg"],
        },
        {
            "title": "Total Recall",
            "year": 1990,
            "vibes": ["Memory implants", "Mars", "Philip K. Dick"],
        },
        {
            "title": "The Fifth Element",
            "year": 1997,
            "vibes": ["Vibrant Visual", "Luc Besson", "Cyberpunk"],
        },
        {
            "title": "Dune: Part Two",
            "year": 2024,
            "vibes": ["Space Opera", "Sci-Fi Epic", "Gritty"],
        },
        # {'title': 'Elysium', 'year': 2013, 'vibes': ['Class warfare', 'Space station', 'Matt Damon']}
    ],
    "Thriller": [
        {
            "title": "The Silence of the Lambs",
            "year": 1991,
            "vibes": ["Psychological", "Dark"],
        },
        {
            "title": "Shutter Island",
            "year": 2010,
            "vibes": ["Psychological", "Suspenseful"],
        },
        {"title": "Gone Girl", "year": 2014, "vibes": ["Psychological", "Suspenseful"]},
        {"title": "No Country for Old Men", "year": 2007, "vibes": ["Intense", "Dark"]},
        {"title": "Nightcrawler", "year": 2014, "vibes": ["Dark", "Psychological"]},
        {
            "title": "Donnie Darko",
            "year": 2001,
            "vibes": ["Mystery", "Psychological Thriller"],
        },
        {"title": "Sicario", "year": 2015, "vibes": ["Intense", "Suspenseful"]},
        {"title": "The Prestige", "year": 2006, "vibes": ["Psychological", "Dark"]},
        {
            "title": "Black Swan",
            "year": 2010,
            "vibes": ["Psychological", "Duality", "Suspenseful"],
        },
        {
            "title": "The Girl with the Dragon Tattoo",
            "year": 2011,
            "vibes": ["Suspenseful", "Dark"],
        },
        # {
        #     "title": "Zodiac",
        #     "year": 2007,
        #     "vibes": ["Serial killer", "Investigation", "1970s"],
        # },
        # {
        #     "title": "Se7en",
        #     "year": 1995,
        #     "vibes": ["Serial killer", "Dark", "Religious themes"],
        # },
        {
            "title": "Fight Club",
            "year": 1999,
            "vibes": ["Identity Crisis", "Twist Ending", "Social Commentary"],
        },
        {
            "title": "Memento",
            "year": 2000,
            "vibes": ["Reverse Chronology", "Psychological Thriller", "Existential"],
        },
        {
            "title": "Rear Window",
            "year": 1954,
            "vibes": ["Hitchcock", "Voyeurism", "Apartment setting"],
        },
        {
            "title": "The Secret in Their Eyes",
            "year": 2009,
            "vibes": ["Dark Romance", "Erotic Thriller", "Tragic"],
        },
        {
            "title": "Joker",
            "year": 2019,
            "vibes": ["Psychological Thriller", "Character-driven", "Tragic"],
        },
        {
            "title": "Cape Fear",
            "year": 1991,
            "vibes": ["Stalker", "Family threat", "De Niro"],
        },
        {
            "title": "Fatal Attraction",
            "year": 1987,
            "vibes": ["Adultery consequences", "Stalker", "Family"],
        },
        # {'title': 'The Hateful Eigt', 'year': 2015, 'vibes': ['Suspense Mystery', 'Gritty', 'Intense']},
        {
            "title": "Misery",
            "year": 1990,
            "vibes": ["Stephen King", "Writer captive", "Kathy Bates"],
        },
        # {'title': 'Mystic River', 'year': 2003, 'vibes': ['Neo-noir', 'Mystery', 'Somber']},
        {
            "title": "What Lies Beneath",
            "year": 2000,
            "vibes": ["Supernatural thriller", "Marriage secrets"],
        },
        {
            "title": "The Others",
            "year": 2001,
            "vibes": ["Ghost Story", "Nicole Kidman", "Twist Ending"],
        },
        {
            "title": "Identity",
            "year": 2003,
            "vibes": ["Multiple personalities", "Motel setting", "Twist"],
        },
        {
            "title": "The Machinist",
            "year": 2004,
            "vibes": ["Insomnia", "Christian Bale", "Psychological"],
        },
        {
            "title": "Shutter",
            "year": 2004,
            "vibes": ["Thai horror-thriller", "Photography", "Guilt"],
        },
        {
            "title": "The Wailing",
            "year": 2016,
            "vibes": ["Korean supernatural", "Village mystery", "Ambiguous"],
        },
        {
            "title": "Burning",
            "year": 2018,
            "vibes": ["Korean Psychological", "Class Tensions", "Mysterious"],
        },
        # {'title': 'Parasite', 'year': 2019, 'vibes': ['Social thriller', 'Class warfare', 'Basement twist']}
    ],
}


def query_qdrant(filter):
    points, _ = qdrant_client.scroll(
        collection_name=QDRANT_MOVIE_COLLECTION_NAME,
        scroll_filter=filter,
        limit=1,
        with_payload=True,
        with_vectors=False,
    )
    return points


qdrant_client = connect_qdrant(QDRANT_API_KEY, QDRANT_ENDPOINT)

for genre, medias in SEEDS_300.items():
    print(f"\n== {genre} ==")
    for m in medias:
        filter = build_qfilter(titles=[m["title"]], release_year=m["year"])
        # print (m['title'])
        points = query_qdrant(filter)
        if points and points[0].payload:
            payload = points[0].payload
            m["poster_url"] = payload["poster_url"]
            m["media_id"] = payload["media_id"]
        else:
            print (f"Missing {m['title']}")
            m["poster_url"] = ""
            m["media_id"] = ""

SEEDS_300


# SEED_MOVIES = {'Action': [{'title': 'Mad Max: Fury Road',
#    'year': 2015,
#    'vibes': ['Fast-paced', 'Action-packed', 'High-stakes'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
#    'media_id': 76341},
#   {'title': 'John Wick',
#    'year': 2014,
#    'vibes': ['Fast-paced', 'Action-packed'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
#    'media_id': 245891},
#   {'title': 'Mission: Impossible - Fallout',
#    'year': 2018,
#    'vibes': ['Espionage', 'High-stakes', 'Fast-paced'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg',
#    'media_id': 353081},
#   {'title': 'Skyfall',
#    'year': 2012,
#    'vibes': ['Espionage', 'High-stakes'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/d0IVecFQvsGdSbnMAHqiYsNYaJT.jpg',
#    'media_id': 37724},
#   {'title': 'Crouching Tiger, Hidden Dragon',
#    'year': 2000,
#    'vibes': ['Action epic', 'Martial arts'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/Abnm1Ws3JH0ReCfEhLMPwPcMcGO.jpg',
#    'media_id': ''},
#   {'title': 'Die Hard',
#    'year': 1988,
#    'vibes': ['High-stakes', 'Action-packed'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/aJCpHDC6RoGz7d1Fzayl019xnxX.jpg',
#    'media_id': 562},
#   {'title': 'Gladiator',
#    'year': 2000,
#    'vibes': ['Action epic', 'Grand journey'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
#    'media_id': 98},
#   {'title': 'The Bourne Ultimatum',
#    'year': 2007,
#    'vibes': ['Espionage', 'Fast-paced'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/15rMz5MRXFp7CP4VxhjYw4y0FUn.jpg',
#    'media_id': 2503},
#   {'title': 'Edge of Tomorrow',
#    'year': 2014,
#    'vibes': ['Fast-paced', 'Action-packed'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/nBM9MMa2WCwvMG4IJ3eiGUdbPe6.jpg',
#    'media_id': 137113},
#   {'title': 'The Dark Knight',
#    'year': 2008,
#    'vibes': ['High-stakes', 'Action-packed'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
#    'media_id': 155},],
#  'Adventure': [{'title': 'Raiders of the Lost Ark',
#    'year': 1981,
#    'vibes': ['Epic scale', 'Grand journey'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg',
#    'media_id': 85},
#   {'title': 'The Lord of the Rings: The Fellowship of the Ring',
#    'year': 2001,
#    'vibes': ['Swashbuckler', 'Grand journey', 'Euphoric'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
#    'media_id': 120},
#   {'title': 'Spirited Away',
#    'year': 2001,
#    'vibes': ['Whimsical', 'Visually-stunning'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
#    'media_id': 129},
#   {'title': 'Pirates of the Caribbean: The Curse of the Black Pearl',
#    'year': 2003,
#    'vibes': ['Whimsical', 'Visually-stunning'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Into the Wild',
#    'year': 2007,
#    'vibes': ['Philosophical', 'Poignant', 'Somber'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Life of Pi',
#    'year': 2012,
#    'vibes': ['Visually-stunning', 'Grand journey'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/iLgRu4hhSr6V1uManX6ukDriiSc.jpg',
#    'media_id': 87827},
#   {'title': 'Up',
#    'year': 2009,
#    'vibes': ['Whimsical', 'Grand journey'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg',
#    'media_id': 14160},
#   {'title': 'Avengers: Endgame',
#    'year': 2019,
#    'vibes': ['Epic scale', 'Visually-stunning'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
#    'media_id': 299534},
#   {'title': 'The Revenant',
#    'year': 2015,
#    'vibes': ['Grand journey', 'Epic scale'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/ji3ecJphATlVgWNY0B0RVXZizdf.jpg',
#    'media_id': 281957},
#   {'title': 'The Secret Life of Walter Mitty',
#    'year': 2013,
#    'vibes': ['Whimsical', 'Grand journey'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/tY6ypjKOOtujhxiSwTmvA4OZ5IE.jpg',
#    'media_id': 116745},
#   {'title': 'Moana',
#    'year': 2016,
#    'vibes': ['Grand journey', 'Visually-stunning'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/9tzN8sPbyod2dsa0lwuvrwBDWra.jpg',
#    'media_id': 277834}],
#  'Comedy': [{'title': 'The Grand Budapest Hotel',
#    'year': 2014,
#    'vibes': ['Quirky', 'Melancholy'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
#    'media_id': ''},
#   {'title': 'Green Book',
#    'year': 2018,
#    'vibes': ['Feel-good', 'Period drama'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Poor Things',
#    'year': 2023,
#    'vibes': ['Absurd', 'Gothic', 'Heartfelt'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Zombieland',
#    'year': 2009,
#    'vibes': ['Light-hearted', 'Satirical'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Mean Girls',
#    'year': 2004,
#    'vibes': ['Coming-of-age', 'Light-hearted'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Jojo Rabbit',
#    'year': 2019,
#    'vibes': ['Satirical', 'Quirky'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/1mqL7VG4Ix8wmxwypmCA1HTHBky.jpg',
#    'media_id': 515001},
#   {'title': 'Anchorman: The Legend of Ron Burgundy',
#    'year': 2004,
#    'vibes': ['Light-hearted', 'Absurd'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/mhZIcRePT7U8viFQVjt1ZjYIsR4.jpg',
#    'media_id': 8699},
#   {'title': 'Hot Fuzz',
#    'year': 2007,
#    'vibes': ['Quirky', 'Satirical'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg',
#    'media_id': 4638},
#   {'title': 'Paddington 2',
#    'year': 2017,
#    'vibes': ['Feel-good', 'Light-hearted'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/1OJ9vkD5xPt3skC6KguyXAgagRZ.jpg',
#    'media_id': 346648},
#   {'title': 'The Big Lebowski',
#    'year': 1998,
#    'vibes': ['Absurd', 'Satirical', 'Neo-Noir'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/gCgt1WARPZaXnq523ySQEUKinCs.jpg',
#    'media_id': 137}],
#  'Crime': [{'title': 'Heat',
#    'year': 1995,
#    'vibes': ['Gritty'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/umSVjVdbVwtx5ryCA2QXL44Durm.jpg',
#    'media_id': 949},
#   {'title': 'Se7en',
#    'year': 1995,
#    'vibes': ['Neo-Noir', 'Plot-twisty'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg',
#    'media_id': 807},
#   {'title': 'The Departed',
#    'year': 2006,
#    'vibes': ['Plot-twisty'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg',
#    'media_id': 1422},
#   {'title': 'Chinatown',
#    'year': 1974,
#    'vibes': ['Slow-burn', 'Neo-Noir'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/kZRSP3FmOcq0xnBulqpUQngJUXY.jpg',
#    'media_id': 829},
#   {'title': 'City of God',
#    'year': 2002,
#    'vibes': ['Gritty'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg',
#    'media_id': 598},
#   {'title': 'Memories of Murder',
#    'year': 2003,
#    'vibes': ['Slow-burn', 'Gritty'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/jcgUjx1QcupGzjntTVlnQ15lHqy.jpg',
#    'media_id': 11423},
#   {'title': 'Oldboy',
#    'year': 2003,
#    'vibes': ['Neo-Noir', 'Plot-twisty'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg',
#    'media_id': 670},
#   {'title': 'The Gentlemen',
#    'year': 2020,
#    'vibes': ['Fast-paced', 'Dark comedy'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
#    'media_id': 155},
#   {'title': 'The Godfather',
#    'year': 1972,
#    'vibes': ['Slow-burn'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
#    'media_id': 238},
#   {'title': 'Prisoners',
#    'year': 2013,
#    'vibes': ['Gritty', 'Plot-twisty'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/jsS3a3ep2KyBVmmiwaz3LvK49b1.jpg',
#    'media_id': 146233},
#   {'title': 'Pulp Fiction',
#    'year': 1994,
#    'vibes': ['Satirical', 'Non-linear narrative'],
#    'poster_url': '',
#    'media_id': ''}],
#  'Drama': [{'title': 'Moonlight',
#    'year': 2016,
#    'vibes': ['Character-driven', 'Emotional'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/rcICfiL9fvwRjoWHxW8QeroLYrJ.jpg',
#    'media_id': 376867},
#   {'title': 'Parasite',
#    'year': 2019,
#    'vibes': ['Social commentary', 'Character-driven'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
#    'media_id': 496243},
#   {'title': 'There Will Be Blood',
#    'year': 2007,
#    'vibes': ['Character-driven', 'Historical'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg',
#    'media_id': 7345},
#   {'title': '12 Years a Slave',
#    'year': 2013,
#    'vibes': ['Historical', 'Emotional'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/xdANQijuNrJaw1HA61rDccME4Tm.jpg',
#    'media_id': 76203},
#   {'title': 'Manchester by the Sea',
#    'year': 2016,
#    'vibes': ['Emotional', 'Character-driven'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/o9VXYOuaJxCEKOxbA86xqtwmqYn.jpg',
#    'media_id': 334541},
#   {'title': 'Nomadland',
#    'year': 2021,
#    'vibes': ['Social commentary', 'Emotional'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/8Vc5EOUEIF1EUXuX9eLFf7BvN3P.jpg',
#    'media_id': 581734},
#   {'title': 'The Social Network',
#    'year': 2010,
#    'vibes': ['Social commentary'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
#    'media_id': 37799},
#   {'title': 'Ford v Ferrari',
#    'year': 2019,
#    'vibes': ['Docudrama', 'Period drama'],
#    'poster_url': '',
#    'media_id': '359724'},
#   {'title': "The King's Speech",
#    'year': 2010,
#    'vibes': ['Historical', 'Emotional', 'Biography'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/pVNKXVQFukBaCz6ML7GH3kiPlQP.jpg',
#    'media_id': 45269},
#   {'title': 'Whiplash',
#    'year': 2014,
#    'vibes': ['Character-driven', 'Emotional'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
#    'media_id': 244786}],
#  'Fantasy': [{'title': "Pan's Labyrinth",
#    'year': 2006,
#    'vibes': ['Dreamlike', 'Mythic', 'Magical'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/s8C4whhKtDaJvMDcyiMvx3BIF5F.jpg',
#    'media_id': 1417},
#   {'title': 'The Lord of the Rings: The Two Towers',
#    'year': 2002,
#    'vibes': ['High fantasy', 'Mythic'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
#    'media_id': 121},
#   {'title': 'KPop Demon Hunters',
#    'year': 2025,
#    'vibes': ['Supernatural', 'Musical'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Harry Potter and the Prisoner of Azkaban',
#    'year': 2004,
#    'vibes': ['Magical'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg',
#    'media_id': 673},
#   {'title': "Howl's Moving Castle",
#    'year': 2004,
#    'vibes': ['Dreamlike', 'Magical'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/TkTPELv4kC3u1lkloush8skOjE.jpg',
#    'media_id': 4935},
#   {'title': 'The Shape of Water',
#    'year': 2017,
#    'vibes': ['Dreamlike', 'Magical'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg',
#    'media_id': 399055},
#   {'title': 'Stardust',
#    'year': 2007,
#    'vibes': ['Magical', 'High fantasy'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/7zbFmxy3DqKYL2M8Hop6uylp2Uy.jpg',
#    'media_id': 2270},
#   {'title': 'The Curious Case of Benjamin Button',
#    'year': 2008,
#    'vibes': ['Whimsical', 'Melancholy'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Big Fish',
#    'year': 2003,
#    'vibes': ['Dreamlike', 'Magical'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/tjK063yCgaBAluVU72rZ6PKPH2l.jpg',
#    'media_id': 587},
#   {'title': 'Avatar',
#    'year': 2009,
#    'vibes': ['Fantasy epic', 'Mythic', 'Reverent'],
#    'poster_url': '',
#    'media_id': ''}],
#  'Horror': [{'title': 'Alien',
#    'year': 1979,
#    'vibes': ['Space opera', 'Monster horror'],
#    'poster_url': '',
#    'media_id': 9552},
#   {'title': 'The Substance',
#    'year': 2024,
#    'vibes': ['Body horror', 'Sardonic'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'American Psycho',
#    'year': 2000,
#    'vibes': ['Slasher', 'Psychological'],
#    'poster_url': '',
#    'media_id': 948},
#   {'title': 'Hereditary',
#    'year': 2018,
#    'vibes': ['Supernatural', 'Twisted'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/4GFPuL14eXi66V96xBWY73Y9PfR.jpg',
#    'media_id': 493922},
#   {'title': 'Get Out',
#    'year': 2017,
#    'vibes': ['Twisted', 'Social commentary'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
#    'media_id': 419430},
#   {'title': 'A Nightmare on Elm Street',
#    'year': 1984,
#    'vibes': ['Supernatural', 'Slasher'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/wGTpGGRMZmyFCcrY2YoxVTIBlli.jpg',
#    'media_id': 377},
#   {'title': 'Midsommar',
#    'year': 2019,
#    'vibes': ['Supernatural', 'Folk horror'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/qt3fqapeo94TfvMyld8P7gkpXLz.jpg',
#    'media_id': 242224},
#   {'title': 'It',
#    'year': 2017,
#    'vibes': ['Supernatural', 'Suspenseful', 'Coming-of-age'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'A Quiet Place',
#    'year': 2018,
#    'vibes': ['Survival', 'Monster horror'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/zwGaUMm0wAqi0wkO7LJDlwoA5LP.jpg',
#    'media_id': 11075},
#   {'title': 'Split',
#    'year': 2017,
#    'vibes': ['Suspenseful', 'Claustrophobic'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/mpgkRPH1GNkMCgdPk2OMyHzAks7.jpg',
#    'media_id': 30497}],
#  'Romance': [{'title': 'When Harry Met Sally...',
#    'year': 1989,
#    'vibes': ['Romantic comedy'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/rFOiFUhTMtDetqCGClC9PIgnC1P.jpg',
#    'media_id': 639},
#   {'title': 'Pride & Prejudice',
#    'year': 2005,
#    'vibes': ['Heartwarming', 'Period drama'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/jnsoq5q98DQaE8yw6WZH0F9dW5G.jpg',
#    'media_id': 4348},
#   {'title': 'The Big Sick',
#    'year': 2017,
#    'vibes': ['Romantic comedy', 'Heartwarming'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/9fJTT8pBxxQsFILJHTtHhdYFr77.jpg',
#    'media_id': 416477},
#   {'title': 'Before Sunrise',
#    'year': 1995,
#    'vibes': ['Bittersweet'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg',
#    'media_id': 76},
#   {'title': 'Call Me by Your Name',
#    'year': 2017,
#    'vibes': ['Bittersweet'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/gXiE0WveDnT0n5J4sW9TMxXF4oT.jpg',
#    'media_id': 398818},
#   {'title': 'Eternal Sunshine of the Spotless Mind',
#    'year': 2004,
#    'vibes': ['Bittersweet'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
#    'media_id': 38},
#   {'title': 'Titanic',
#    'year': 1997,
#    'vibes': ['Tragic love'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
#    'media_id': 597},
#   {'title': 'La La Land',
#    'year': 2016,
#    'vibes': ['Bittersweet', 'Visually-stunning'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
#    'media_id': 313369},
#   {'title': 'The Notebook',
#    'year': 2004,
#    'vibes': ['Tragic love', 'Heartwarming'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
#    'media_id': 11036},
#   {'title': 'Midnight in Paris',
#    'year': 2011,
#    'vibes': ['Nostalgic', 'Metaphorical', 'Romantic comedy'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Notting Hill',
#    'year': 1999,
#    'vibes': ['Romantic comedy', 'Heartwarming'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/hHRIf2XHeQMbyRb3HUx19SF5Ujw.jpg',
#    'media_id': 509}],
#  'Science Fiction': [{'title': 'Inception',
#    'year': 2010,
#    'vibes': ['Mind-bending', 'Cerebral', 'Psychological'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
#    'media_id': 27205},
#   {'title': 'The Matrix',
#    'year': 1999,
#    'vibes': ['Cyberpunk', 'Mind-bending'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/p96dm7sCMn4VYAStA6siNz30G1r.jpg',
#    'media_id': 603},
#   {'title': 'Blade Runner 2049',
#    'year': 2017,
#    'vibes': ['Cyberpunk', 'Thought-provoking', 'Dystopian'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
#    'media_id': 335984},
#   {'title': 'Arrival',
#    'year': 2016,
#    'vibes': ['Thought-provoking'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
#    'media_id': 329865},
#   {'title': 'Ex Machina',
#    'year': 2015,
#    'vibes': ['Thought-provoking'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg',
#    'media_id': 264660},
#   {'title': 'Children of Men',
#    'year': 2006,
#    'vibes': ['Dystopian', 'Thought-provoking'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/8Xgvmx7WWc7Z9Ws9RAYk7uya2kh.jpg',
#    'media_id': 9693},
#   {'title': 'Everything Everywhere All at Once',
#    'year': 2022,
#    'vibes': ['Quirky', 'Existential', 'Mind-bending'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/dvjqlp2sAhUeFjUOfQDgqwpphHj.jpg',
#    'media_id': 2493},
#   {'title': 'Gattaca',
#    'year': 1997,
#    'vibes': ['Dystopian', 'Thought-provoking'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/eSKr5Fl1MEC7zpAXaLWBWSBjgJq.jpg',
#    'media_id': 782},
#   {'title': 'Gravity',
#    'year': 2013,
#    'vibes': ['Claustrophobic', 'Visually Stunning', 'Tense'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Her',
#    'year': 2013,
#    'vibes': ['Poignant', 'Thought-provoking'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Ghost in the Shell',
#    'year': 1995,
#    'vibes': ['Cyberpunk', 'Thought-provoking'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/9gC88zYUBARRSThcG93MvW14sqx.jpg',
#    'media_id': 9323}],
#  'Thriller': [{'title': 'The Silence of the Lambs',
#    'year': 1991,
#    'vibes': ['Psychological', 'Dark'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
#    'media_id': 274},
#   {'title': 'Shutter Island',
#    'year': 2010,
#    'vibes': ['Psychological', 'Suspenseful'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg',
#    'media_id': 11324},
#   {'title': 'Gone Girl',
#    'year': 2014,
#    'vibes': ['Psychological', 'Suspenseful'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/ts996lKsxvjkO2yiYG0ht4qAicO.jpg',
#    'media_id': 210577},
#   {'title': 'No Country for Old Men',
#    'year': 2007,
#    'vibes': ['Intense', 'Dark'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/6d5XOczc226jECq0LIX0siKtgHR.jpg',
#    'media_id': 6977},
#   {'title': 'Nightcrawler',
#    'year': 2014,
#    'vibes': ['Dark', 'Psychological'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg',
#    'media_id': 242582},
#   {'title': 'Donnie Darko',
#    'year': 2001,
#    'vibes': ['Mystery', 'Psychological Thriller'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'Sicario',
#    'year': 2015,
#    'vibes': ['Intense', 'Suspenseful'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg',
#    'media_id': 273481},
#   {'title': 'The Prestige',
#    'year': 2006,
#    'vibes': ['Psychological', 'Dark'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/2ZOzyhoW08neG27DVySMCcq2emd.jpg',
#    'media_id': 1124},
#   {'title': 'Black Swan',
#    'year': 2010,
#    'vibes': ['Psychological', 'Duality', 'Suspenseful'],
#    'poster_url': '',
#    'media_id': ''},
#   {'title': 'The Girl with the Dragon Tattoo',
#    'year': 2011,
#    'vibes': ['Suspenseful', 'Dark'],
#    'poster_url': 'https://image.tmdb.org/t/p/w500/8bokS83zGdhaXgN9tjidUKmAftW.jpg',
#    'media_id': 65754}]
#  }
