name: CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ---------- SDKs ----------
  sdk-ts:
    name: TS SDK (orval) — generate & check drift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - run: pnpm -v
      - run: pnpm install

      - name: Generate TS SDK (orval)
        working-directory: packages/ts-sdk
        run: pnpm run generate

      - name: Fail if TS SDK drifted
        run: |
          git diff --exit-code -- packages/ts-sdk/src/index.ts || \
          (echo "::error ::TS SDK out of date. Run 'pnpm -C packages/ts-sdk run generate' and commit the changes."; exit 1)

  sdk-py:
    name: Python SDK (openapi-python-client) — generate & check drift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Generate Python SDK
        working-directory: apps/api
        run: |
          uv run openapi-python-client generate \
            --path ../../packages/schemas/openapi.yaml \
            --output-path ../../packages/py-sdk \
            --meta none --overwrite

      - name: Fail if Python SDK drifted
        run: |
          git diff --exit-code -- packages/py-sdk || \
          (echo "::error ::Python SDK out of date. Regenerate and commit."; exit 1)

  # ---------- Node (web + any TS pkgs) ----------
  node:
    name: Node — lint • typecheck • test • build
    runs-on: ubuntu-latest
    needs: [sdk-ts]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - run: pnpm -v
      - run: pnpm install

      - name: Lint
        run: pnpm -w run lint || pnpm -C apps/web run lint

      - name: Typecheck
        run: pnpm -w run typecheck || pnpm -C apps/web run typecheck

      - name: Test
        run: pnpm -w run test --if-present || pnpm -C apps/web run test --if-present

      - name: Build
        run: pnpm -w run build || pnpm -C apps/web run build

  # ---------- Python API ----------
  python-api:
    name: Python API — ruff • tests
    runs-on: ubuntu-latest
    needs: [sdk-py]
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            apps/api/.venv
          key: uv-${{ runner.os }}-api-${{ hashFiles('apps/api/pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-api-

      - name: Sync deps (all groups)
        run: uv sync --all-groups

      - name: Ruff (lint)
        run: uv run ruff check .

      # Uncomment once you add tests
      - name: Tests (pytest)
        run: uv run pytest -q
        continue-on-error: true

  # ---------- Python Worker ----------
  python-worker:
    name: Python Worker — ruff • tests
    runs-on: ubuntu-latest
    needs: [sdk-py]
    defaults:
      run:
        working-directory: apps/worker
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            apps/worker/.venv
          key: uv-${{ runner.os }}-worker-${{ hashFiles('apps/worker/pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-worker-

      - name: Sync deps (all groups)
        run: uv sync --all-groups

      - name: Ruff (lint)
        run: uv run ruff check .

      # Uncomment once you add tests
      - name: Tests (pytest)
        run: uv run pytest -q
        continue-on-error: true
